
server:
  port: 8081

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: 'fornecedor'
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

